# Pi "disassembler" — notebook-friendly, no Excel needed.
# Goal: given the first N bytes of π in base-16 (BBP-accessed), try to explain each byte
# as a simple 2-input operation on earlier bytes (a tiny "opcode" set).
#
# IMPORTANT: This is NOT claiming π is generated by these ops.
# It is a pattern-mining / rule-discovery toy: "can I predict byte[t] from byte[i], byte[j]?"
#
# Requirements: Python 3.9+, numpy, pandas, matplotlib

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

# ---------------------------
# 1) BBP: get hex digits of π
# ---------------------------

def _series(j: int, n: int) -> float:
    """
    BBP helper term: S_j(n) = sum_{k=0}^∞ 16^{n-k} / (8k+j)
    computed as: finite modular part + convergent tail.
    Returns fractional part in [0,1).
    """
    # modular (finite) sum
    s = 0.0
    for k in range(n + 1):
        r = 8 * k + j
        s = (s + pow(16, n - k, r) / r) % 1.0
    # tail
    t = 0.0
    k = n + 1
    # tail converges fast; 25-30 terms is plenty for n ~ 0..few thousand
    for _ in range(30):
        r = 8 * k + j
        t += (16.0 ** (n - k)) / r
        k += 1
    return (s + t) % 1.0

def pi_hex_digits(start: int, count: int) -> list[int]:
    """
    Return `count` hex digits of π starting at position `start` after the hex point.
    start=0 gives digits of π's fractional part in hex (π = 3.<hex>...).
    Each digit is an int 0..15.
    """
    out = []
    for n in range(start, start + count):
        x = (4*_series(1,n) - 2*_series(4,n) - _series(5,n) - _series(6,n)) % 1.0
        out.append(int(x * 16.0))
    return out

def pi_bytes_from_hex(n_bytes: int, start_hex_digit: int = 0) -> np.ndarray:
    """
    Make bytes by taking pairs of hex digits: byte = 16*d0 + d1.
    start_hex_digit=0 corresponds to 0x24,0x3F,0x6A,0x88,... (since π hex is 3.243F6A88...)
    """
    digs = pi_hex_digits(start_hex_digit, n_bytes * 2)
    b = np.array([16*digs[2*i] + digs[2*i+1] for i in range(n_bytes)], dtype=np.int64)
    return b

# ---------------------------
# 2) Tiny opcode set
# ---------------------------

def op_add(a,b):  return (a + b) & 0xFF
def op_xor(a,b):  return (a ^ b) & 0xFF
def op_diff(a,b): return abs(int(a) - int(b)) & 0xFF

OPS = {
    "ADD2": op_add,
    "XOR2": op_xor,
    "DIFF2": op_diff,
}

# ---------------------------
# 3) Disassembler: explain byte[t]
# ---------------------------

def disassemble_bytes(bytes_arr: np.ndarray, lookback: int = 64):
    """
    For each t, try to find i< t, j < t so that op(bytes[i], bytes[j]) == bytes[t].
    Search pairs within last `lookback` steps (speed + locality).
    If multiple matches exist, pick the one with smallest lag (t-max(i,j)), then arbitrary.
    """
    b = bytes_arr
    N = len(b)

    rows = []
    op_counts = Counter()
    matched = np.zeros(N, dtype=int)

    for t in range(N):
        if t < 2:
            rows.append(dict(t=t, byte=int(b[t]), opcode="PUSH", src1=np.nan, src2=np.nan, lag=np.nan,
                             matched=0, detail="seed"))
            op_counts["PUSH"] += 1
            continue

        best = None  # (lag, opcode, i, j)
        lo = max(0, t - lookback)

        target = int(b[t])
        for name, fn in OPS.items():
            for i in range(lo, t):
                ai = int(b[i])
                for j in range(lo, t):
                    if i == j:  # allow i==j if you want, but keep simple
                        continue
                    val = fn(ai, int(b[j]))
                    if val == target:
                        lag = t - max(i, j)
                        cand = (lag, name, i, j)
                        if (best is None) or (cand < best):
                            best = cand
                # tiny speedup: early exit if perfect lag=1 found
                if best is not None and best[0] == 1:
                    break
            if best is not None and best[0] == 1:
                break

        if best is None:
            rows.append(dict(t=t, byte=target, opcode="PUSH", src1=np.nan, src2=np.nan, lag=np.nan,
                             matched=0, detail="no exact 8-bit rule found"))
            op_counts["PUSH"] += 1
        else:
            lag, name, i, j = best
            matched[t] = 1
            op_counts[name] += 1
            rows.append(dict(
                t=t, byte=target, opcode=name, src1=i, src2=j, lag=lag, matched=1,
                detail=f"{name}(b[{i}]={int(b[i])}, b[{j}]={int(b[j])}) = {target}"
            ))

    df = pd.DataFrame(rows)
    return df, op_counts

# ---------------------------
# 4) Run + plots
# ---------------------------

def run_pi_disassembler(n_bytes=128, lookback=64, start_hex_digit=0, outdir=None):
    pi_b = pi_bytes_from_hex(n_bytes, start_hex_digit=start_hex_digit)
    df, op_counts = disassemble_bytes(pi_b, lookback=lookback)

    match_rate = df["matched"].mean()
    print(f"n_bytes={n_bytes}, lookback={lookback}, start_hex_digit={start_hex_digit}")
    print(f"exact-match rate: {match_rate:.3f}")

    # Plot 1: π byte trace
    plt.figure(figsize=(10,3.8))
    plt.plot(df["t"], df["byte"])
    plt.title("π byte trace (BBP hex→byte)")
    plt.xlabel("t (byte index)")
    plt.ylabel("byte value")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    if outdir:
        plt.savefig(f"{outdir}/pi_byte_trace.png", dpi=160)
    plt.show()

    # Plot 2: match-over-time
    plt.figure(figsize=(10,2.8))
    plt.plot(df["t"], df["matched"])
    plt.title("Match-over-time (exact 8-bit rule found)")
    plt.xlabel("t")
    plt.ylabel("matched (1=yes)")
    plt.ylim(-0.05, 1.05)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    if outdir:
        plt.savefig(f"{outdir}/match_over_time.png", dpi=160)
    plt.show()

    # Plot 3: opcode counts
    counts = pd.Series(op_counts).sort_values(ascending=False)
    plt.figure(figsize=(7.5,3.5))
    plt.bar(counts.index, counts.values)
    plt.title("Opcode counts (exact matches only)")
    plt.xticks(rotation=35, ha="right")
    plt.ylabel("count")
    plt.grid(True, axis="y", alpha=0.3)
    plt.tight_layout()
    if outdir:
        plt.savefig(f"{outdir}/opcode_counts.png", dpi=160)
    plt.show()

    # Summary
    print(counts.to_string())

    return df, pi_b, counts

# Example:
# df, pi_b, counts = run_pi_disassembler(n_bytes=96, lookback=64, start_hex_digit=0)
